Master
AzureAD/azure-activedirectory-library-for-android pull request #1576
Opened 2020-12-21 23:16 UTC by AdamBJohnsonx

Please make sure every Pull Request has the following information:

* A reference to a related issue in your repository (mandatory)
* A description of the changes proposed in the pull request
* @mentions of the person required for reviewing proposed changes (optional)

2020-12-21 23:19 UTC, AdamBJohnsonx commented on userappwithbroker/build.gradle
> +    distImplementation("com.microsoft.aad:adal:3.1.0") {
```suggestion
    distImplementation("com.microsoft.aad:adal:3.1.2") {
```

2020-12-21 23:40 UTC, AdamBJohnsonx commented on userappwithbroker/build.gradle
> +    distImplementation("com.microsoft.aad:adal:3.1.0") {
```suggestion
    distImplementation("com.microsoft.aad:adal:3.1.2") {
```

2021-01-04 20:23 UTC, gitaumoses4 approved these changes
Looks good.

2021-01-04 20:26 UTC, tanmaymanolkar1 requested changes

2021-01-04 20:26 UTC, tanmaymanolkar1 commented on adal/build.gradle
> +    distApi("com.microsoft.identity:common:3.0.6") {
the common would be 3.0.8 as of now.

2021-03-18 16:22 UTC, closed without merging